version: '3.9'
services:
    node:
      container_name: spotisession-api
      image: 'node:latest'
      working_dir: /home/node/app
      env_file:
        - .env
      command:
        - /bin/sh
        - '-c'
        - 'npm install && npm start'
      ports:
        - '3000:3000'
      volumes:
        - './src:/home/node/app'
      links:
        - mongo
    mongo:
      container_name: spotisession-db
      image: mongo
      ports:
        - "27017:27017"